if (BUILD_EXAMPLES)
    file(COPY ${CMAKE_CURRENT_SOURCE_DIR}/ssl.p12 DESTINATION ${PROJECT_BINARY_DIR}/bin)

    file(GLOB TEST_SRC_LIST ${CMAKE_CURRENT_SOURCE_DIR}/test_*.cpp)
    foreach(TEST_SRC ${TEST_SRC_LIST})
        get_filename_component(TESTER ${TEST_SRC} NAME_WE)
        message(STATUS "add tester :${TESTER}")
        add_executable(${TESTER} ${TEST_SRC})
        target_link_libraries(${TESTER} PRIVATE ${PROJECT_NAME})
        set_target_properties(${TESTER} PROPERTIES RUNTIME_OUTPUT_DIRECTORY ${PROJECT_BINARY_DIR}/bin)
    endforeach()
endif ()

if (BUILD_TESTING)
    find_package(GTest REQUIRED)
    file(GLOB UNIT_TEST_SOURCES CONFIGURE_DEPENDS ${CMAKE_CURRENT_SOURCE_DIR}/unit/*.cpp)
    add_executable(unit_tests ${UNIT_TEST_SOURCES})
    target_link_libraries(unit_tests PRIVATE ${PROJECT_NAME} GTest::GTest GTest::Main)
    if (ENABLE_COVERAGE)
        target_compile_options(unit_tests PRIVATE --coverage -O0 -g)
        set_property(TARGET unit_tests APPEND_STRING PROPERTY LINK_FLAGS " --coverage")
    endif ()
    set_target_properties(unit_tests PROPERTIES RUNTIME_OUTPUT_DIRECTORY ${PROJECT_BINARY_DIR}/bin)
    add_test(NAME core_utilities COMMAND unit_tests)
endif ()
